# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskalg',
            name='alg',
        ),
        migrations.RemoveField(
            model_name='taskalg',
            name='task',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='ml_app.Task'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskAlg',
        ),
    ]
