# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_auto_20171115_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='ml_app.Task'),
        ),
    ]
